{"version":"3.8.0","messages":["\nAn error occurred while loading ./spec/pry_debugging_spec.rb.\n\u001b[31mFailure/Error: \u001b[0mbinding.binding.pry\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  private method `binding' called for #<Binding:0x00000001a0ce58>\u001b[0m\n\u001b[31m  Did you mean?  __binding__\u001b[0m\n\u001b[36m# ./spec/pry_debugging_spec.rb:8:in `block in <top (required)>'\u001b[0m\n\u001b[36m# ./spec/pry_debugging_spec.rb:4:in `<top (required)>'\u001b[0m\n"],"examples":[],"summary":{"duration":0.000254107,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}